#ifndef ERROR

#define CTCP_SUCCESS 0
#define CTCP_CHECK_ERRNO 1
#define CTCP_INTERNAL_ERROR 2
#define CTCP_SERVER_SETUP_ERROR 3
#define CTCP_CLIENT_SETUP_ERROR 4
#define CTCP_SERVER_SEND_ERROR 5
#define CTCP_SERVER_RECV_ERROR 6
#define CTCP_CLIENT_SEND_ERROR 7
#define CTCP_CLIENT_RECV_ERROR 8

#endif	// !ERROR
